function [] = enter()
	[nodes, beams, mats, geoms, qloads, ploads, incload] = lesinput();
	%  constructConnectivityMatrix(beams);

	beams = assignBeamLength(beams, nodes)
	beams = assignBeamElasticity(beams, mats)

	%{
	constructStiffnessMatrix(...
		[1 2 3 4 5 6 7;...
		 1 1 1 2 4 3 5;...
		 4 3 2 3 3 5 4],...
		[4 2;...
		 2 4])
	%}
end
